title: The official blog of shiftXchange
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1992481
  lightness: 0.7867884
  brandStrength: 0.3625134
  brandColors:
    - '#f5f5f5'
    - '#3f51b5'
    - '#ff4081'
    - '#a8a8a8'
    - '#212f37'
  rhythmicContrast: 0.4462943
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: generationy
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.66117
layout_spectrum: 0.3635875
