name: ShiftXchange blog
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40874
title: The official blog of shiftXchange
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#3f51b5'
    - '#b3b3b3'
    - '#ff5252'
    - '#000000'
  brandStrength: 0.3625134
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
