name: generationy
favicon: null
layout_spectrum: 0.9160450072959065
typography_spectrum: 0.7959573161788285
title: Generation Y
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5440339324995875
  lightness: 0.1287392182275653
  saturation: 0.5885439040139318
  rhythmicContrast: 0.2718914174474776
purpose: []
