name: generationy
favicon: null
layout_spectrum: 0.91942
typography_spectrum: 0.66117
title: Generation Y
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#3f51b5'
    - '#ff4081'
    - '#a8a8a8'
    - '#212f37'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
